Table Header:
[<th style="width: 90px;">Nation</th>, <th style="width: 90px;"><a href="/wiki/Element" title="Element">Element</a></th>, <th><a class="mw-redirect" href="/wiki/Archon" title="Archon">Archon</a> (Vessel)</th>, <th>Ideal</th>, <th>Governing Body
</th>]
Table Content: [{'Nation': None, 'Element': None, 'Archon (Vessel)': None, 'Ideal': None, 'Governing Body': None}, {'Nation': <td><a href="/wiki/Mondstadt" title="Mondstadt"><img alt="Emblem Mondstadt" data-image-key="Emblem_Mondstadt.png" data-image-name="Emblem Mondstadt.png" decoding="async" height="60" loading="lazy" src="https://static.wikia.nocookie.net/gensin-impact/images/8/80/Emblem_Mondstadt.png/revision/latest/scale-to-width-down/60?cb=20201116194623" width="60"/></a><br/><a href="/wiki/Mondstadt" title="Mondstadt">Mondstadt</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Anemo" title="Anemo"><img alt="Anemo" data-image-key="Element_Anemo.svg" data-image-name="Element Anemo.svg" decoding="async" height="60" loading="lazy" src="https://static.wikia.nocookie.net/gensin-impact/images/1/10/Element_Anemo.svg/revision/latest/scale-to-width-down/60?cb=20220119211128" width="60"/></a><br/><a href="/wiki/Anemo" title="Anemo">Anemo</a></span>
</td>, 'Archon (Vessel)': <td><a href="/wiki/Barbatos" title="Barbatos">Barbatos</a> (<a href="/wiki/Venti" title="Venti">Venti</a>)
</td>, 'Ideal': <td>Freedom<sup class="reference" id="cite_ref-Farewell_2-0"><a href="#cite_note-Farewell-2">[2]</a></sup>
</td>, 'Governing Body': <td><a href="/wiki/Knights_of_Favonius" title="Knights of Favonius">Knights of Favonius</a>
</td>}, {'Nation': <td><a href="/wiki/Liyue" title="Liyue"><img alt="Emblem Liyue" data-image-key="Emblem_Liyue.png" data-image-name="Emblem Liyue.png" decoding="async" height="60" loading="lazy" src="https://static.wikia.nocookie.net/gensin-impact/images/f/f8/Emblem_Liyue.png/revision/latest/scale-to-width-down/60?cb=20201116194654" width="60"/></a><br/><a href="/wiki/Liyue" title="Liyue">Liyue</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Geo" title="Geo"><img alt="Geo" class="lazyload" data-image-key="Element_Geo.svg" data-image-name="Element Geo.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/9/9b/Element_Geo.svg/revision/latest/scale-to-width-down/60?cb=20220119211105" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Geo" title="Geo">Geo</a></span>
</td>, 'Archon (Vessel)': <td><a href="/wiki/Morax" title="Morax">Morax</a> (<a href="/wiki/Zhongli" title="Zhongli">Zhongli</a>)
</td>, 'Ideal': <td>Contracts<sup class="reference" id="cite_ref-Farewell_2-1"><a href="#cite_note-Farewell-2">[2]</a></sup>
</td>, 'Governing Body': <td><a href="/wiki/Liyue_Qixing" title="Liyue Qixing">Liyue Qixing</a>
</td>}, {'Nation': <td><a href="/wiki/Inazuma" title="Inazuma"><img alt="Emblem Inazuma" class="lazyload" data-image-key="Emblem_Inazuma.png" data-image-name="Emblem Inazuma.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/9/9e/Emblem_Inazuma.png/revision/latest/scale-to-width-down/60?cb=20230127155005" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Inazuma" title="Inazuma">Inazuma</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Electro" title="Electro"><img alt="Electro" class="lazyload" data-image-key="Element_Electro.svg" data-image-name="Element Electro.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/f/ff/Element_Electro.svg/revision/latest/scale-to-width-down/60?cb=20220119211156" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Electro" title="Electro">Electro</a></span>
</td>, 'Archon (Vessel)': <td><a class="mw-redirect" href="/wiki/Raiden_Ei" title="Raiden Ei">Beelzebul</a> (<a href="/wiki/Raiden_Shogun" title="Raiden Shogun">Raiden Shogun</a>)
</td>, 'Ideal': <td>Eternity<sup class="reference" id="cite_ref-Farewell_2-2"><a href="#cite_note-Farewell-2">[2]</a></sup>
</td>, 'Governing Body': <td><a href="/wiki/Inazuma_Shogunate" title="Inazuma Shogunate">Inazuma Shogunate</a>
</td>}, {'Nation': <td><a href="/wiki/Sumeru" title="Sumeru"><img alt="Emblem Sumeru" class="lazyload" data-image-key="Emblem_Sumeru.png" data-image-name="Emblem Sumeru.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/3/38/Emblem_Sumeru.png/revision/latest/scale-to-width-down/60?cb=20220718183140" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Sumeru" title="Sumeru">Sumeru</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Dendro" title="Dendro"><img alt="Dendro" class="lazyload" data-image-key="Element_Dendro.svg" data-image-name="Element Dendro.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/7/73/Element_Dendro.svg/revision/latest/scale-to-width-down/60?cb=20220119211226" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Dendro" title="Dendro">Dendro</a></span>
</td>, 'Archon (Vessel)': <td><a href="/wiki/Lesser_Lord_Kusanali" title="Lesser Lord Kusanali">Buer</a> (<a href="/wiki/Nahida" title="Nahida">Nahida</a>)
</td>, 'Ideal': <td>Wisdom<sup class="reference" id="cite_ref-Preview_3-0"><a href="#cite_note-Preview-3">[3]</a></sup>
</td>, 'Governing Body': <td><a href="/wiki/Sumeru_Akademiya" title="Sumeru Akademiya">Sumeru Akademiya</a>
</td>}, {'Nation': <td><a href="/wiki/Fontaine" title="Fontaine"><img alt="Emblem Nation Unknown" class="lazyload" data-image-key="Emblem_Nation_Unknown.png" data-image-name="Emblem Nation Unknown.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/b/b0/Emblem_Nation_Unknown.png/revision/latest/scale-to-width-down/60?cb=20220619184541" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Fontaine" title="Fontaine">Fontaine</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Hydro" title="Hydro"><img alt="Hydro" class="lazyload" data-image-key="Element_Hydro.svg" data-image-name="Element Hydro.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/8/80/Element_Hydro.svg/revision/latest/scale-to-width-down/60?cb=20220119211435" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Hydro" title="Hydro">Hydro</a></span>
</td>, 'Archon (Vessel)': <td><a href="/wiki/Focalors" title="Focalors">Focalors</a><sup class="reference" id="cite_ref-Preview_3-1"><a href="#cite_note-Preview-3">[3]</a></sup>
</td>, 'Ideal': <td>Justice<sup class="reference" id="cite_ref-Preview_3-2"><a href="#cite_note-Preview-3">[3]</a></sup>
</td>, 'Governing Body': <td>Unknown
</td>}, {'Nation': <td><a href="/wiki/Natlan" title="Natlan"><img alt="Emblem Nation Unknown" class="lazyload" data-image-key="Emblem_Nation_Unknown.png" data-image-name="Emblem Nation Unknown.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/b/b0/Emblem_Nation_Unknown.png/revision/latest/scale-to-width-down/60?cb=20220619184541" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Natlan" title="Natlan">Natlan</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Pyro" title="Pyro"><img alt="Pyro" class="lazyload" data-image-key="Element_Pyro.svg" data-image-name="Element Pyro.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/2/2c/Element_Pyro.svg/revision/latest/scale-to-width-down/60?cb=20220119211527" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Pyro" title="Pyro">Pyro</a></span>
</td>, 'Archon (Vessel)': <td><a href="/wiki/Murata" title="Murata">Murata</a>
</td>, 'Ideal': <td>War<sup class="reference" id="cite_ref-Preview_3-3"><a href="#cite_note-Preview-3">[3]</a></sup>
</td>, 'Governing Body': <td>Unknown
</td>}, {'Nation': <td><a href="/wiki/Snezhnaya" title="Snezhnaya"><img alt="Emblem Nation Unknown" class="lazyload" data-image-key="Emblem_Nation_Unknown.png" data-image-name="Emblem Nation Unknown.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/b/b0/Emblem_Nation_Unknown.png/revision/latest/scale-to-width-down/60?cb=20220619184541" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Snezhnaya" title="Snezhnaya">Snezhnaya</a>
</td>, 'Element': <td><span style="display: inline-block; text-align:center;"><a href="/wiki/Cryo" title="Cryo"><img alt="Cryo" class="lazyload" data-image-key="Element_Cryo.svg" data-image-name="Element Cryo.svg" data-src="https://static.wikia.nocookie.net/gensin-impact/images/7/72/Element_Cryo.svg/revision/latest/scale-to-width-down/60?cb=20220119211508" decoding="async" height="60" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="60"/></a><br/><a href="/wiki/Cryo" title="Cryo">Cryo</a></span>
</td>, 'Archon (Vessel)': <td>The <a href="/wiki/Tsaritsa" title="Tsaritsa">Tsaritsa</a>
</td>, 'Ideal': <td>Unknown<sup class="reference" id="cite_ref-4"><a href="#cite_note-4">[Note 1]</a></sup>
</td>, 'Governing Body': <td>Unknown
</td>}]
