Table Header:
[<th>Icon</th>, <th>Type</th>, <th class="unsortable">Info
</th>]
Table Content: [{'Icon': None, 'Type': None, 'Info': None}, {'Icon': <td><a href="/wiki/Swords" title="Swords"><img alt="Icon Sword" data-image-key="Icon_Sword.png" data-image-name="Icon Sword.png" decoding="async" height="64" loading="lazy" src="https://static.wikia.nocookie.net/gensin-impact/images/8/81/Icon_Sword.png/revision/latest/scale-to-width-down/64?cb=20210413210800" width="64"/></a>
</td>, 'Type': <td><a class="mw-redirect" href="/wiki/Swords" title="Swords">Swords</a>
</td>, 'Info': <td>Sword attacks are the middle ground of melee weapons. The damage and speed of their attacks are comparable to those of Polearms, though with a shorter reach.
</td>}, {'Icon': <td><a href="/wiki/Claymores" title="Claymores"><img alt="Icon Claymore" data-image-key="Icon_Claymore.png" data-image-name="Icon Claymore.png" decoding="async" height="64" loading="lazy" src="https://static.wikia.nocookie.net/gensin-impact/images/6/66/Icon_Claymore.png/revision/latest/scale-to-width-down/64?cb=20210413210803" width="64"/></a>
</td>, 'Type': <td><a class="mw-redirect" href="/wiki/Claymores" title="Claymores">Claymores</a>
</td>, 'Info': <td>Claymores attacks hit slower than melee weapons like <a class="mw-redirect" href="/wiki/Swords" title="Swords">Swords</a> and <a class="mw-redirect" href="/wiki/Polearms" title="Polearms">Polearms</a>, but deal much more damage per swing. Due to being considered <a href="/wiki/Blunt_Attack" title="Blunt Attack">Blunt Attacks</a>, Claymore attacks deal increased damage to <a href="/wiki/Geo" title="Geo">Geo</a> objects, such as monsters' shields.
</td>}, {'Icon': <td><a href="/wiki/Polearms" title="Polearms"><img alt="Icon Polearm" class="lazyload" data-image-key="Icon_Polearm.png" data-image-name="Icon Polearm.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/6/6a/Icon_Polearm.png/revision/latest/scale-to-width-down/64?cb=20210413210804" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="64"/></a>
</td>, 'Type': <td><a class="mw-redirect" href="/wiki/Polearms" title="Polearms">Polearms</a>
</td>, 'Info': <td>Polearms have fast attacks, long forward reach, and deal moderate damage per hit.
</td>}, {'Icon': <td><a href="/wiki/Catalysts" title="Catalysts"><img alt="Icon Catalyst" class="lazyload" data-image-key="Icon_Catalyst.png" data-image-name="Icon Catalyst.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/2/27/Icon_Catalyst.png/revision/latest/scale-to-width-down/64?cb=20210413210802" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="64"/></a>
</td>, 'Type': <td><a class="mw-redirect" href="/wiki/Catalysts" title="Catalysts">Catalysts</a>
</td>, 'Info': <td>Due to their magical nature, all Normal and Charged Attacks performed with a Catalyst are considered elemental damage. The element of the damage depends on the wielder's natural element/vision.
</td>}, {'Icon': <td><a href="/wiki/Bows" title="Bows"><img alt="Icon Bow" class="lazyload" data-image-key="Icon_Bow.png" data-image-name="Icon Bow.png" data-src="https://static.wikia.nocookie.net/gensin-impact/images/8/81/Icon_Bow.png/revision/latest/scale-to-width-down/64?cb=20210413210801" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="64"/></a>
</td>, 'Type': <td><a class="mw-redirect" href="/wiki/Bows" title="Bows">Bows</a>
</td>, 'Info': <td>Bows boast long-ranged attacks, with Charged Attacks that are capable of hitting monsters as far as the eye can see with the proper aim. A fully-Charged Attack deals elemental damage.
</td>}]
