int pinA=12;
int pinB=8;
int pinC=4;
int pinD=6;
int pinE=7;
int pinF=11; 
int pinG=3;
int pinDP=5;
int switch1=2;
int switch10=9;
int switch100=10;
int switch1000=13;
void displayNum(int num, int digit, int state){
  switch (num){
    case 0:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,state);
    digitalWrite(pinF,state);
    digitalWrite(pinG,0);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 1:
    digitalWrite(pinA,0);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,0);
    digitalWrite(pinE,0);
    digitalWrite(pinF,0);
    digitalWrite(pinG,0);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 2:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,0);
    digitalWrite(pinD,state);
    digitalWrite(pinE,state);
    digitalWrite(pinF,0);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 3:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,0);
    digitalWrite(pinF,0);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 4:
    digitalWrite(pinA,0);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,0);
    digitalWrite(pinE,0);
    digitalWrite(pinF,state);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 5:
    digitalWrite(pinA,state);
    digitalWrite(pinB,0);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,0);
    digitalWrite(pinF,state);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 6:
    digitalWrite(pinA,state);
    digitalWrite(pinB,0);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,state);
    digitalWrite(pinF,state);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 7:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,0);
    digitalWrite(pinE,0);
    digitalWrite(pinF,0);
    digitalWrite(pinG,0);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 8:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,state);
    digitalWrite(pinF,state);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
    case 9:
    digitalWrite(pinA,state);
    digitalWrite(pinB,state);
    digitalWrite(pinC,state);
    digitalWrite(pinD,state);
    digitalWrite(pinE,0);
    digitalWrite(pinF,state);
    digitalWrite(pinG,state);
    if(digit==1){
      digitalWrite(switch1,0);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==10){
      digitalWrite(switch1,1);
      digitalWrite(switch10,0);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,1);
    }
    if(digit==100){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,0);
      digitalWrite(switch1000,1);
    }
    if(digit==1000){
      digitalWrite(switch1,1);
      digitalWrite(switch10,1);
      digitalWrite(switch100,1);
      digitalWrite(switch1000,0);
    }
    break;
  }
}
void displayDP(int digit, int state){
  switch(digit){
    case 1:
    digitalWrite(pinDP,1);
    digitalWrite(switch1,0);
    digitalWrite(switch10,1);
    digitalWrite(switch100,1);
    digitalWrite(switch1000,1);
    break;
    case 10:
    digitalWrite(pinDP,1);
    digitalWrite(switch1,1);
    digitalWrite(switch10,0);
    digitalWrite(switch100,1);
    digitalWrite(switch1000,1);
    break;
    case 100:
    digitalWrite(pinDP,1);
    digitalWrite(switch1,1);
    digitalWrite(switch10,1);
    digitalWrite(switch100,0);
    digitalWrite(switch1000,1);
    break;
    case 1000:
    digitalWrite(pinDP,1);
    digitalWrite(switch1,1);
    digitalWrite(switch10,1);
    digitalWrite(switch100,1);
    digitalWrite(switch1000,0);
    break;
  }
}
int a=0;
int b=0;
int c=0;
int d=0;
int e=0;
unsigned long restriction=1;
int numDisplay[4]={0,0,0,0};
int digitDisplay[4]={1,10,100,1000};
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  pinMode(pinA,OUTPUT);
  pinMode(pinB,OUTPUT);
  pinMode(pinC,OUTPUT);
  pinMode(pinD,OUTPUT);
  pinMode(pinE,OUTPUT);
  pinMode(pinF,OUTPUT);
  pinMode(pinG,OUTPUT);
  pinMode(pinDP,OUTPUT);
  pinMode(switch1,OUTPUT);
  pinMode(switch10,OUTPUT);
  pinMode(switch100,OUTPUT);
  pinMode(switch1000,OUTPUT);
}
void loop(){
  for(int a=0; a<4; a++){
    displayNum(numDisplay[a],digitDisplay[a],1);
    delay(5);
    if(millis()/1000>=restriction){
      restriction=restriction+1;
      b++;
      numDisplay[0]=b;
      if(b>=10){
        b=0;
        c++;
        numDisplay[0]=b;
        numDisplay[1]=c;
        if(c>=6){
          c=0;
          d++;
          numDisplay[1]=c;
          numDisplay[2]=d;
          if(d>=10){
            d=0;
            e++;
            numDisplay[2]=d;
            numDisplay[3]=e;
            if(e>=6){
              e=0;
              numDisplay[3]=e;
            }
          }
        }
      }
    }
  }

}
